ARG python_version=3.8
ARG python_version=3.9
ARG python_version=3.10
ARG python_version=3.11
ARG python_version=3.12
FROM python:$python_version-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirement.txt
EXPOSE 8000
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000","--reload"]
